function[N, N_row, derN] = Shape_function_M(xi, eta)

N1e = -((1-xi)*(1-eta)*(1+xi+eta))/4;
N2e = -((1+xi)*(1-eta)*(1-xi+eta))/4;
N3e = -((1+xi)*(1+eta)*(1-xi-eta))/4;
N4e = -((1-xi)*(1+eta)*(1+xi-eta))/4;
N5e = ((1-xi)*(1+xi)*(1-eta))/2;
N6e = ((1+xi)*(1-eta)*(1+eta))/2;
N7e = ((1-xi)*(1+xi)*(1+eta))/2;
N8e = ((1-xi)*(1-eta)*(1+eta))/2;

N = [diag([N1e N1e N1e]) ...
     diag([N2e N2e N2e]) ...
     diag([N3e N3e N3e]) ...
     diag([N4e N4e N4e]) ...
     diag([N5e N5e N5e]) ...
     diag([N6e N6e N6e]) ...
     diag([N7e N7e N7e]) ...
     diag([N8e N8e N8e])];
N_row = [N1e N2e N3e N4e N5e N6e N7e N8e];

derN(1,:) = [((2*xi+eta)*(1-eta))/4 ...
             -((-2*xi+eta)*(1-eta))/4 ...
             ((2*xi+eta)*(1+eta))/4 ...
             -((-2*xi+eta)*(1+eta))/4 ...
             -xi*(1-eta) ...
             ((1-eta)*(1+eta)/2) ...
             -xi*(1+eta) ...
             -((1-eta)*(1+eta))/2];

derN(2,:) = [((1-xi)*(xi+2*eta))/4 ...
             -((1+xi)*(xi-2*eta))/4 ...
             ((1+xi)*(xi+2*eta))/4 ...
             -((1-xi)*(xi-2*eta))/4 ...
             -((1-xi)*(1+xi))/2 ...
             -(1+xi)*eta ...
             ((1-xi)*(1+xi))/2 ...
             -(1-xi)*eta];

end
